version: '3'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8088:8088
      - 443:443
    volumes:
      - ./build/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - service

  mysql:
    container_name: some-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: gudemaoning147
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /root/mysql/mysql_data:/var/lib/mysql

  service:
    restart: always
    build: ./service
    working_dir: /service
    ports:
      - "8080:8080"
    volumes:
      - ./service:/service
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql